subclass_code = {
  "id" => 299799,
  "default_option" => nil,
  "description" => "Oralsurgeons",
  "import_ref" => "20397",
  "wc_employee_id" => "WC0049",
  "starr_gl_enabled" => false,
  "chubb_gl_class" => "45",
  "mc_group" => nil,
  "show_mc_group" => nil,
  "skip_ui" => false,
  "liberty_gl_exposure" => "SqFeetofArea",
  "liberty_gl_description" => "MedicalOffices",
  "sub_class_code_ref" => "1545",
  "sectors" => [],
  "cna_industry_code" => nil,
  "appetite_codes" => {
    "cna_wc_code" => "8021-2-50",
    "rps_cl_code" => "HEALTHCARE_MEDICAL",
    "btis_gl_code" => nil,
    "cna_bop_code" => "80212_5065121F",
    "chubb_gl_code" => "45",
    "chubb_pl_code" => nil,
    "guard_ca_code" => nil,
    "guard_wc_code" => "WC0049",
    "acuity_ca_code" => "OF-66561-621111-8621",
    "hiscox_gl_code" => nil,
    "hiscox_pl_code" => nil,
    "amtrust_wc_code" => "WC0049",
    "liberty_gl_code" => "66561",
    "hartford_gl_code" => "65671",
    "hartford_wc_code" => "65671",
    "liberty_bop_code" => "88621",
    "chubb_sci_gl_code" => "598",
    "chubb_sci_wc_code" => "598",
    "hartford_bop_code" => "65671",
    "liberty_cpsp_code" => nil,
    "chubb_sci_bop_code" => "598",
    "cna_bop_code_value" => "80212_50",
    "cna_bop_class_codes" => "65121F",
    "progressive_ca_code" => nil,
    "rt_specialty_gl_code" => "66561",
    "cna_bop_industry_code" => "OF",
    "liberty_gl_description" => "MedicalOffices",
    "chubb_sci_semci_gl_code" => nil,
    "chubb_sci_semci_bop_code" => nil,
    "liberty_gl_exposure_basis" => "SqFeetofArea"
  },
  "class_code" => {
    "id" => 186008,
    "description" => "Officesandclinicsofdentists",
    "import_ref" => "20397"
  }
}

SUBCLASSCODE = {
  "default_option" => nil,
  "description" => "Oralsurgeons",
  "import_ref" => "20397",
  "wc_employee_id" => "WC0049",
  "starr_gl_enabled" => false,
  "chubb_gl_class" => "45",
  "mc_group" => nil,
  "show_mc_group" => nil,
  "skip_ui" => false,
  "liberty_gl_exposure" => "SqFeetofArea",
  "liberty_gl_description" => "MedicalOffices",
  "sub_class_code_ref" => "1545",
  "sectors" => [],
  "cna_industry_code" => nil,
  "appetite_codes" => {
    "cna_wc_code" => "8021-2-50",
    "rps_cl_code" => "HEALTHCARE_MEDICAL",
    "btis_gl_code" => nil,
    "cna_bop_code" => "80212_5065121F",
    "chubb_gl_code" => "45",
    "chubb_pl_code" => nil,
    "guard_ca_code" => nil,
    "guard_wc_code" => "WC0049",
    "acuity_ca_code" => "OF-66561-621111-8621",
    "hiscox_gl_code" => nil,
    "hiscox_pl_code" => nil,
    "amtrust_wc_code" => "WC0049",
    "liberty_gl_code" => "66561",
    "hartford_gl_code" => "65671",
    "hartford_wc_code" => "65671",
    "liberty_bop_code" => "88621",
    "chubb_sci_gl_code" => "598",
    "chubb_sci_wc_code" => "598",
    "hartford_bop_code" => "65671",
    "liberty_cpsp_code" => nil,
    "chubb_sci_bop_code" => "598",
    "cna_bop_code_value" => "80212_50",
    "cna_bop_class_codes" => "65121F",
    "progressive_ca_code" => nil,
    "rt_specialty_gl_code" => "66561",
    "cna_bop_industry_code" => "OF",
    "liberty_gl_description" => "MedicalOffices",
    "chubb_sci_semci_gl_code" => nil,
    "chubb_sci_semci_bop_code" => nil,
    "liberty_gl_exposure_basis" => "SqFeetofArea"
  }
}

require 'rails_helper'

RSpec.describe User do
  it 'checks' do
    expect(subclass_code).to include(SUBCLASSCODE)
  end
end